name: Generate Snake Animation

on:
  schedule:
    # Runs at 12:00 PM UTC every day
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: "Baseldiab"  # Make sure your username is quoted
          outputs: dist/snake.svg

      - name: Commit and push the snake
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated snake animation"
          file_pattern: dist/snake.svg
